config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root "home#index"
    resources :groups, only: [:index, :new, :create] do
      resources :expenses, only: [:index, :new, :create] 
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user, class_name: 'User', dependent: :destroy
  has_many :groups
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true
  belongs_to :user, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :name, presence: true, length: { maximum: 250 }
  has_many :groups, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :remember_me)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @group = current_user.groups.find(params[:group_id])
  end

  def new
    @group = Group.find(params[:group_id])
    @expense = Expense.new
  end

  def create
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.new(name: exp_params[:name], amount: exp_params[:amount], user_id: current_user.id)
    if @expense.save
      flash[:notice] = 'Expense successfully completed.'
      redirect_to group_expenses_path(@group)
    else
      flash[:notice] = 'Invalid Expense!'
    end
  end

  private

  def exp_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    p gro_params
    p current_user.id
    # @group = Group.new(name: params[:group][:name], icon: params[:group][:icon], author: current_user)
    @group = Group.new(gro_params)
    @group.user_id = current_user.id
    if @group.save
      p 'save method'
      # flash[:notice] = 'Successfully created Category.'
      redirect_to groups_path, notice: 'Category was successfully created.'
    else
      p 'not save'
      flash[:notice] = 'Invalid Category. Please try again.'
    end
  end

  private

  def gro_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_expense_form.html.erb
<%= form_for :Expense, url: group_expense_path(@group), method: :post do |form|  %>
  <div class='expense-form'>
    <%= form.text_field :name, class: 'expense_name_field expense_form_field', placeholder: 'Name' %>
    <%= form.text_field :amount, class: 'expense_amount_field expense_form_field', placeholder: 'Amount' %>
    <%= form.submit "Submit", class: 'expense_form_btn expense_form_field' %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<%= render partial: 'shared/navbar', locals: { heading: 'EXPENSES', back_path: expenses_path} %>
<ul class="expenses-container-part">
<% @group.expenses.each do |expense| %>
  <li class='expenses-container'>
    <span><%= expense.name %></span>
    <span>$<%= expense.amount %></span>
  </li>
<% end %>
</ul>
<%= link_to "Create Expense", new_group_expense_path(@group), class: 'expense-create-btn' %>

app/views/expenses/new.html.erb
<%= render partial: 'shared/navbar', locals: { heading: 'CREATE EXPENS', back_path: group_expenses_path(@group) } %>
<%= render partial: 'expense_form' %>

app/views/groups/_group_form.html.erb
<%= render partial: 'shared/navbar', locals: {heading: 'CREATE CATERGORY', back_path: groups_path } %>
<%= form_with model: @group, url: groups_path do |form| %>
<div class="group-form">
<%= form.text_field :name, class: 'group-form-field group_name_field', placeholder: 'Category Name' %>
Insert Icon: <%= form.text_field :icon, class: 'group-form-field group_name_field', placeholder: 'Icon path' %>
<%= form.submit "Submit", class: 'group-form-field group-form-btn' %>
</div>
<% end %>

app/views/groups/index.html.erb
<%= render partial: 'shared/navbar', locals: { heading: 'Categories', back_path: groups_path } %>
<ul class="groups-section">
<% @groups.includes(:expenses).each do |gro| %>
    <li class="groups-section-item">
      <ul class="groups-container">
       <li class="groups-image">
        <img src="<%= group.icon %>" class="group-image">
        </li>
        <li class="groups-detail">
          <span><%= link_to gro.name, group_expenses_path(group_id: gro.id) %></span>
          <span><%= gro.created_at.strftime("%d-%m-%y") %></span>
        </li>
        <li class="groups-amount">
          <span>$<%= gro.total_expenses_amount %></span>
        </li>
        </ul>
        </li>
        <% end %>
        </ul>  
        <div class='create-group-btn-container'>
          <%= link_to "create group", new_group_path, class: 'create-group-btn' %>
          </div>

app/views/groups/new.html.erb
<%= render 'groups/group_form', {group:@group}%>

app/views/home/index.htm.erb
<section id="first-page">
  <header>
    <h1>Budget App</h1>
  </header>

  <nav>
    <%= link_to "LOG IN ", new_user_session_path, class: "bttn blue-bttn" %>
    <%= link_to "SIGN UP ", new_user_registration_path, class: "bttn blue-bttn grey-bttn" %>
  </nav>
</section>

app/views/home/index.html.erb
<section id="first-page">
  <header>
    <h1>Budget App</h1>
  </header>

  <nav>
    <%= link_to "LOG IN ", new_user_session_path, class: "bttn blue-bttn" %>
    <%= link_to "SIGN UP ", new_user_registration_path, class: "bttn blue-bttn grey-bttn" %>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BadgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <%= link_to image_tag("back-icon.png"), back_path, class: 'back-btn'%>
   <h3 class="nav-heading"><%= heading %></h3>
   <%if user_signed_in?%>
     <% button_to "sign out", destroy_user_session_path, method: :delete, class: 'sign_out_btn'%>
   <% else %>
     <%= link_to "", class: "empty"%>
   <% end %>    
</nav>